version: "3.7"

services:

  infinispan-example1:
    image: infinispan-example:0.0.1
    container_name: infinispan-example1
    env_file: .env
    environment:
      - INFINISPAN_TCP_PORT=7800
      - HOST_ADDRESS=192.168.1.201
      - HOST_PROT=7800
      - CONSUL_HOST=192.168.1.201
      - CONSUL_PORT=8500
    network_mode: bridge
    #networks:
    #  - bridge

 #   depends_on: 
 #     - consul
    ports:
      - "192.168.1.201:7800:7800"
      - "192.168.1.201:8080:8080"

  infinispan-example2:
    image: infinispan-example:0.0.1
    container_name: infinispan-example2
    env_file: .env
    environment:
      - INFINISPAN_TCP_PORT=7801
      - HOST_ADDRESS=192.168.1.201
      - HOST_PROT=7801
      - CONSUL_HOST=192.168.1.201
      - CONSUL_PORT=8500    
    network_mode: bridge

#    networks:
#      - bridge

#    depends_on: 
#      - consul
    ports:
      - "192.168.1.201:7801:7800"
      - "192.168.1.201:8081:8080"

#  consul:
#    image: consul
#    ports:
#      - 8500:8500
#      - 8600:8600
#    command: ["agent", "-dev", "-ui", "-http-port","8500", "-client", "0.0.0.0"]

