version: "3.7"

services:

  infinispan-example1:
    image: infinispan-example:0.0.1
    container_name: infinispan-example1
    env_file: .env
    environment:
      - INFINISPAN_TCP_PORT=7800
    network_mode: bridge
    ports:
      - 7800:7800
      - 8080:8080

  infinispan-example2:
    image: infinispan-example:0.0.1
    container_name: infinispan-example2
    env_file: .env
    environment:
      - INFINISPAN_TCP_PORT=7801
    network_mode: bridge
    ports:
      - 7801:7800
      - 8081:8080
