spring:
  application:
    name: infinispan-example
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

server:
  port: 8080

logging:
  level:
    org.infinispan.interceptors: OFF
    org.jgroups: OFF
    ru.crystals: INFO
